Add gdl.conf, adjust Wi-Fi management, etc.

diff --git a/gdl b/gdl
--- a/gdl
+++ b/gdl
@@ -1,255 +1,13 @@
 #!/bin/bash
 #
 # Golden Drake Linux (GDL): an Arch installer for gamers and game developers!
+#
 # Copyright (C) 2020-2021 Golden Drake Studios: goldendrakestudios.com
 # Forked originally from the Anarchy installer: anarchyinstaller.gitlab.io
 #
 # shellcheck disable=SC1090,SC2154,SC2034,SC2155
 
-readonly DEFAULT_BACKTITLE="Golden Drake Linux v1.0.0"
-readonly GDL_DIR='/usr/share/gdl'
-readonly LOG_FILE='/root/gdl.log'
-readonly SSL_KEY="$(openssl rand -base64 32)"
-readonly VM_TYPE="$(systemd-detect-virt)"
-readonly BLACK='\e[0;30m' # color constants for use with 'echo'
-readonly RED='\e[0;31m'
-readonly GREEN='\e[0;32m'
-readonly YELLOW='\e[0;33m'
-readonly BLUE='\e[0;34m'
-readonly MAGENTA='\e[0;35m'
-readonly CYAN='\e[0;36m'
-readonly WHITE='\e[0;37m'
-readonly BOLD_BLACK='\e[1;30m'
-readonly BOLD_RED='\e[1;31m'
-readonly BOLD_GREEN='\e[1;32m'
-readonly BOLD_YELLOW='\e[1;33m'
-readonly BOLD_BLUE='\e[1;34m'
-readonly BOLD_MAGENTA='\e[1;35m'
-readonly BOLD_CYAN='\e[1;36m'
-readonly BOLD_WHITE='\e[1;37m'
-readonly COLOR_RESET='\e[m'
-readonly I='\Z3*\Zn' # item (to mark unordered list items in dialogs)
-TITLE=''
-BACKTITLE=''
-INCLUDE_BACKTITLE='true'
-NEW_HOSTNAME=''
-NEW_USERNAME=''
-NEW_USER_FULL_NAME=''
-NEW_PW=''
-RELOAD_LANG_TEXT='false'
-WIFI_AVAILABLE='false'
-BLUETOOTH_AVAILABLE='false'
-USB='none'
-BATTERY=''
-DRIVE=''
-SWAP_SIZE=''
-ROOT=''
-BOOT=''
-ESP_MNT=''
-MOUNTED='false'
-ENCRYPTED='false'
-GPT=''
-UEFI=''
-KEYMAP=''
-ZONE=''
-LANG_FILE="${GDL_DIR}/lang/english.conf"
-
-# Color scheme for installer
-tput civis
-echo -en '\e]P0000000' #darkblack (black)
-echo -en '\e]P1800000' #darkred (maroon)
-echo -en '\e]P200A86B' #darkgreen (jade)
-echo -en '\e]P3DA9100' #darkyellow/brown (harvest gold)
-echo -en '\e]P4082567' #darkblue (sapphire)
-echo -en '\e]P5AB274F' #darkmagenta (amaranth purple)
-echo -en '\e]P63AA8C1' #darkcyan (moonstone)
-echo -en '\e]P7C0C0C0' #darkwhite/lightgrey (silver)
-echo -en '\e]P8555555' #lightblack/darkgrey (Davy's gray)
-echo -en '\e]P9FF2400' #lightred (scarlet)
-echo -en '\e]PA50C878' #lightgreen (emerald)
-echo -en '\e]PBD4AF37' #lightyellow (metallic gold)
-echo -en '\e]PC318CE7' #lightblue (bleu de France)
-echo -en '\e]PDE0115F' #lightmagenta (ruby)
-echo -en '\e]PE7FFFD4' #lightcyan (aquamarine)
-echo -en '\e]PFE5E4E2' #lightwhite (platinum)
-setterm -background black -foreground yellow -store
-tput cnorm
-
-# Default non-AUR packages to install
-BASE_PACKAGES='
-  acpi
-  alsa-utils
-  arch-wiki-docs
-  arch-wiki-lite
-  asciiquarium
-  atril
-  audacious
-  base-devel
-  bash
-  bash-completion
-  btrfs-progs
-  bzip2
-  cheese
-  celluloid
-  cmatrix
-  cool-retro-term
-  coreutils
-  cowsay
-  cpupower
-  dhcpcd
-  dialog
-  dosfstools
-  e2fsprogs
-  ffmpegthumbnailer
-  file-roller
-  fortune-mod
-  figlet
-  file
-  filesystem
-  findutils
-  galculator
-  gamemode lib32-gamemode
-  gawk
-  gcc-libs
-  gcolor2
-  gettext
-  git
-  git-lfs
-  glibc
-  gnome-characters
-  gnome-keyring
-  grep
-  grub
-  gst-libav
-  gst-plugins-base
-  gst-plugins-good
-  gst-plugins-bad
-  gst-plugins-ugly
-  gufw
-  gvfs
-  gvfs-mtp
-  gvfs-smb
-  gvim
-  gzip
-  inetutils
-  iproute2
-  iputils
-  jp2a
-  libreoffice-fresh
-  libsecret
-  licenses
-  lightdm
-  lightdm-gtk-greeter
-  lightdm-gtk-greeter-settings
-  linux
-  linux-firmware
-  linux-headers
-  lolcat
-  lvm2
-  man-db
-  man-pages
-  mesa lib32-mesa
-  neofetch
-  networkmanager
-  network-manager-applet
-  noto-fonts
-  noto-fonts-emoji
-  noto-fonts-extra
-  ntfs-3g
-  openssh
-  p7zip
-  pacman
-  pacman-contrib
-  pavucontrol
-  pciutils
-  pipewire
-  poppler-data
-  procps-ng
-  ps_mem
-  psmisc
-  pulseaudio
-  pulseaudio-alsa
-  redshift
-  reflector
-  sed
-  shadow
-  sl
-  soundfont-fluid
-  sudo
-  systemd
-  systemd-sysvcompat
-  tar
-  terminator
-  texinfo
-  tree
-  ttf-dejavu
-  ufw
-  unrar
-  unzip
-  util-linux
-  vi
-  vkd3d lib32-vkd3d
-  wget
-  wtf
-  xdg-user-dirs
-  xfce4
-  xfce4-goodies
-  xorg-apps
-  xorg-server
-  xorg-xinit
-  xterm
-  xz
-  zip '
-
-# If Lutris is selected, all these will be installed as they're often necessary
-# or helpful for running non-Steam Windows games/apps (such as Battle.net).
-# Main source: https://github.com/lutris/docs/blob/master/WineDependencies.md
-LUTRIS_PACKAGES='
-  lutris
-  wine-staging
-  giflib lib32-giflib
-  libpng lib32-libpng
-  libldap lib32-libldap
-  gnutls lib32-gnutls
-  mpg123 lib32-mpg123
-  openal lib32-openal
-  v4l-utils lib32-v4l-utils
-  libpulse lib32-libpulse
-  libgpg-error lib32-libgpg-error
-  alsa-plugins lib32-alsa-plugins
-  alsa-lib lib32-alsa-lib
-  libjpeg-turbo lib32-libjpeg-turbo
-  sqlite lib32-sqlite
-  libxcomposite lib32-libxcomposite
-  libxinerama lib32-libxinerama
-  libgcrypt lib32-libgcrypt
-  ncurses lib32-ncurses
-  opencl-icd-loader lib32-opencl-icd-loader
-  libxslt lib32-libxslt
-  libva lib32-libva
-  gtk3 lib32-gtk3
-  gst-plugins-base-libs lib32-gst-plugins-base-libs
-  vulkan-icd-loader lib32-vulkan-icd-loader
-  wine-gecko
-  wine-mono
-  winetricks
-  samba
-  sdl lib32-sdl
-  fluidsynth lib32-fluidsynth
-  libva-vdpau-driver lib32-libva-vdpau-driver
-  libcanberra-pulse lib32-libcanberra-pulse '
-
-# Packages to install after the base install (esp. AUR software)
-AUR_AND_OPTIONAL_PACKAGES='
-  boxes
-  cbonsai
-  matcha-gtk-theme
-  mugshot
-  no-more-secrets
-  surfn-icons-git
-  toilet
-  xcursor-breeze
-  xfce-superkey-git '
+source /etc/gdl.conf
 
 # Appends a given string or command output stream to the log file
 log() {
@@ -262,35 +20,26 @@ log() {
   fi
 }
 
-# Enables a given systemd service
-enable_service() {
-  if arch-chroot /mnt systemctl enable "$1"; then
-    log "Enabled systemd service '$1'"
-  else
-    log "ERROR: Failed to enable systemd service '$1'"
-  fi
-}
-
 # Custom cowsay function
 dragonsay() {
-  if "${INCLUDE_BACKTITLE}"; then
-    cowsay -f dragon "$1"
-  else
+  if "${REDUCE_EXTRANEOUS_TEXT}"; then
     echo -e "$1\n"
+  else
+    cowsay -f dragon "$1"
   fi
 }
 
 # Custom dialog function
 dialog() {
-  if "${INCLUDE_BACKTITLE}"; then
+  if "${REDUCE_EXTRANEOUS_TEXT}"; then
+    /usr/bin/dialog --stdout --colors --title " ${TITLE} " "$@"
+  else
     BACKTITLE="${DEFAULT_BACKTITLE}"
     if [[ -n "${BATTERY}" ]]; then
       BACKTITLE+=" | Battery: $(cat "${BATTERY}"/capacity)%"
     fi
     /usr/bin/dialog --stdout --colors --backtitle "${BACKTITLE}" --title \
       " ${TITLE} " "$@"
-  else
-    /usr/bin/dialog --stdout --colors --title " ${TITLE} " "$@"
   fi
 }
 
@@ -331,6 +80,15 @@ load_bar() {
   } | dialog --gauge "\n$1" 9 79 0
 }
 
+# Enables a given systemd service
+enable_service() {
+  if arch-chroot /mnt systemctl enable "$1"; then
+    log "Enabled systemd service '$1'"
+  else
+    log "ERROR: Failed to enable systemd service '$1'"
+  fi
+}
+
 # Handles a sudden exit caused by the user pressing Ctrl+C
 force_quit() {
   log "User force quit the installation"
@@ -344,10 +102,15 @@ force_quit() {
 
 initialize() {
   source "${LANG_FILE}"
+
+  # Check for root privileges (this should never be an issue)
   if (( $(id -u) != 0 )); then
     dragonsay "Sorry, this script requires root privileges (e.g., sudo)."
     exit 1
-  elif [[ ! -f "${LOG_FILE}" ]]; then # first (automatic) launch of gdl
+  fi
+
+  # First (automatic) run: exit so user can run other commands first if desired
+  if [[ ! -f "${LOG_FILE}" ]]; then
     touch "${LOG_FILE}"
     sed -i 's/^#Color$/Color/' /etc/pacman.conf
     sed -i 's/^#CheckSpace$/CheckSpace/' /etc/pacman.conf
@@ -358,46 +121,47 @@ initialize() {
     clear
     dragonsay "${intro_msg}"
     echo -e "${shell_prompt_msg2}"
-    exit # let user run other commands, if desired, before install truly begins
+    exit
   fi
-  log "Initializing installer"
+
+  # Second (or later) run: prepare for installation
+  log "Initializing installer..."
+  systemctl start NetworkManager.service
+  trap force_quit SIGINT # call 'force_quit' when Ctrl+C is pressed
   set -o pipefail # ensure $? remembers failures from piped commands
   [[ -d /tmp/gdl ]] || mkdir /tmp/gdl
   if (( $(tput lines) < 25 )) || grep -q 'accessibility=' /proc/cmdline; then
-    INCLUDE_BACKTITLE='false'
+    REDUCE_EXTRANEOUS_TEXT='true'
   fi
-  if lsblk | grep 'run' | grep -qo 'sd.'; then
-    USB="$(lsblk | grep 'run' | grep -o 'sd.')"
+  if [[ -z "$(ip addr | grep -Eq 'wlp|wlo|wlan')" ]]; then
+    WIFI_AVAILABLE='false'
   fi
   if dmesg | grep -qi 'blue'; then
     BLUETOOTH_AVAILABLE='true'
+  fi
+  if lsblk | grep 'run' | grep -qo 'sd.'; then
+    USB="$(lsblk | grep 'run' | grep -o 'sd.')"
   fi
   if [[ -d /sys/class/power_supply/BAT0 ]]; then
     BATTERY='/sys/class/power_supply/BAT0'
   elif [[ -d /sys/class/power_supply/BAT1 ]]; then
     BATTERY='/sys/class/power_supply/BAT1'
   fi
-  if [[ -n "$(ip addr | grep -E 'wlp|wlo|wlan' | awk '{print $2}' |
-        sed 's/://' | head -n 1)" ]]; then
-    WIFI_AVAILABLE='true'
-  fi
   if [[ "${VM_TYPE}" == 'none' ]]; then
     if lspci | grep VGA | grep -iq 'nvidia'; then
-      readonly DEFAULT_GPU_DRIVER='nvidia'
       readonly GPU_CHIPSET='NVIDIA'
+      readonly DEFAULT_GPU_DRIVER='nvidia'
     elif lspci | grep VGA | grep -Eq 'ATI|AMD'; then
-      readonly DEFAULT_GPU_DRIVER='xf86-video-ati'
       readonly GPU_CHIPSET='AMD/ATI'
+      readonly DEFAULT_GPU_DRIVER='xf86-video-ati'
     elif lspci | grep VGA | grep -q 'Intel'; then
-      readonly DEFAULT_GPU_DRIVER='xf86-video-intel'
       readonly GPU_CHIPSET='Intel'
+      readonly DEFAULT_GPU_DRIVER='xf86-video-intel'
     else
-      readonly DEFAULT_GPU_DRIVER='xf86-video-vesa'
       readonly GPU_CHIPSET='Unknown'
+      readonly DEFAULT_GPU_DRIVER='xf86-video-vesa'
     fi
   fi
-  trap force_quit SIGINT # execute trap when Ctrl+C is pressed (SIGINT)
-  systemctl start NetworkManager.service
 }
 
 set_language() {
@@ -494,10 +258,21 @@ update_mirrors() {
   TITLE="${mirror_op_msg}"
   local mirrors_option editor
 
-  if ! nc -zw1 1.1.1.1 443; then
-    nmtui # attempt to connect to Wi-Fi if not already connected to the internet
-  fi
+  # Ensure an internet connection is established before continuing
+  while ! nc -zw 1 1.1.1.1 443; do
+    if "${WIFI_AVAILABLE}" && [[ -n "${WIFI_SSID}" ]] &&
+        (nmcli dev wifi connect "${WIFI_SSID}" password "${WIFI_PASSWORD}" \
+           &>/dev/null &
+         load_bar "${wait_load}\n\n \Z1> \Z2nmcli dev wifi connect\Zn"); then
+      log "Successfully connected to Wi-Fi"
+    else
+      nmtui
+    fi
+    sleep 1
+  done
   timedatectl set-ntp true # ensure system clock is accurate
+
+  # Present options for updating mirrors
   while true; do
     if mirrors_option="$(dialog --no-cancel --ok-button "${ok}" --menu \
         "\n${mirror_msg0}" 12 60 3 \
@@ -576,28 +351,29 @@ set_time_zone() {
 
   while true; do
     # shellcheck disable=SC2086
-    ZONE="$(dialog --no-cancel --ok-button "${ok}" --menu "\n${zone_msg0}" \
-      18 60 10 ${zonelist})"
+    TIME_ZONE="$(dialog --no-cancel --ok-button "${ok}" --menu \
+      "\n${zone_msg0}" 18 60 10 ${zonelist})"
     if find /usr/share/zoneinfo -maxdepth 1 -type d | sed -n -e 's!^.*/!!p' |
-        grep -q "${ZONE}"; then
-      sublist="$(find /usr/share/zoneinfo/"${ZONE}" -maxdepth 1 |
-        sed -n -e 's!^.*/!!p' | sort | sed 's/$/ ->/g' | grep -v "${ZONE}")"
+        grep -q "${TIME_ZONE}"; then
+      sublist="$(find /usr/share/zoneinfo/"${TIME_ZONE}" -maxdepth 1 |
+        sed -n -e 's!^.*/!!p' | sort | sed 's/$/ ->/g' |
+        grep -v "${TIME_ZONE}")"
       # shellcheck disable=SC2086
       if subzone="$(dialog --ok-button "${ok}" --cancel-button "${back}" \
           --menu "\n${zone_msg1}" 18 60 10 ${sublist})"; then
-        if find /usr/share/zoneinfo/"${ZONE}" -maxdepth 1 -type d |
+        if find /usr/share/zoneinfo/"${TIME_ZONE}" -maxdepth 1 -type d |
             sed -n -e 's!^.*/!!p' | grep -q "${subzone}"; then
-          sublist="$(find /usr/share/zoneinfo/"${ZONE}/${subzone}" \
+          sublist="$(find /usr/share/zoneinfo/"${TIME_ZONE}/${subzone}" \
             -maxdepth 1 | sed -n -e 's!^.*/!!p' | sort | sed 's/$/ ->/g' |
             grep -v "${subzone}")"
           # shellcheck disable=SC2086
           if subsubzone="$(dialog --ok-button "${ok}" --cancel-button \
               "${back}" --menu "\n${zone_msg1}" 15 60 7 ${sublist})"; then
-            ZONE="${ZONE}/${subzone}/${subsubzone}"
+            TIME_ZONE="${TIME_ZONE}/${subzone}/${subsubzone}"
             break
           fi
         else
-          ZONE="${ZONE}/${subzone}"
+          TIME_ZONE="${TIME_ZONE}/${subzone}"
           break
         fi
       fi
@@ -605,7 +381,7 @@ set_time_zone() {
       break
     fi
   done
-  log "Set time zone to: ${ZONE}"
+  log "Set time zone to: ${TIME_ZONE}"
 }
 
 prepare_drives() {
@@ -643,14 +419,14 @@ prepare_drives() {
     elif [[ "${partition_method}" != "${method_manual}" ]]; then
       rm /tmp/gdl/part.sh &>/dev/null # remove old temp file (if one exists)
       # shellcheck disable=SC2028
-      if "${INCLUDE_BACKTITLE}"; then
-        echo "dialog --stdout --colors --backtitle \"${BACKTITLE}\" --title \" \
-${TITLE} \" --ok-button \"${ok}\" --cancel-button \"${cancel}\" --menu \
-\"\n${drive_msg}\n\n ${drive_menu_header}\" 16 60 5 \\" >/tmp/gdl/part.sh
-      else
+      if "${REDUCE_EXTRANEOUS_TEXT}"; then
         echo "dialog --stdout --colors --title \" ${TITLE} \" --ok-button \
 \"${ok}\" --cancel-button \"${cancel}\" --menu \"\n${drive_msg}\n\n \
 ${drive_menu_header}\" 16 60 5 \\" >/tmp/gdl/part.sh
+      else
+        echo "dialog --stdout --colors --backtitle \"${BACKTITLE}\" --title \" \
+${TITLE} \" --ok-button \"${ok}\" --cancel-button \"${cancel}\" --menu \
+\"\n${drive_msg}\n\n ${drive_menu_header}\" 16 60 5 \\" >/tmp/gdl/part.sh
       fi
       lsblk -nio NAME,SIZE,TYPE | grep -E "disk|raid[0-9]+$" |
         sed 's/[^[:alnum:]_., ]//g' | column -t | sort -k 1,1 | uniq |
@@ -979,16 +755,16 @@ manual_partition_menu() {
       grep -Ev "${USB}|loop[0-9]+|sr[0-9]+|fd[0-9]+" |
       sed 's/[^[:alnum:]_., -]//g' | column -t | sort -k 1,1 | uniq)"
     device_count="$(wc -l <<<"${dev_list}")"
-    if "${INCLUDE_BACKTITLE}"; then
-      # shellcheck disable=SC2028
-      echo "dialog --stdout --colors --backtitle \"${BACKTITLE}\" --title \
-\" ${TITLE} \" --ok-button \"${edit}\" --cancel-button \"${cancel}\" --menu \
-\"\n${manual_part_msg}\n\n${dev_menu_header}\" 21 68 9 \\" >/tmp/gdl/part.sh
-    else
+    if "${REDUCE_EXTRANEOUS_TEXT}"; then
       # shellcheck disable=SC2028
       echo "dialog --stdout --colors --title \" ${TITLE} \" --ok-button \
 \"${edit}\" --cancel-button \"${cancel}\" --menu \"\n${manual_part_msg}\n
 ${dev_menu_header}\" 20 68 8 \\" >/tmp/gdl/part.sh
+    else
+      # shellcheck disable=SC2028
+      echo "dialog --stdout --colors --backtitle \"${BACKTITLE}\" --title \
+\" ${TITLE} \" --ok-button \"${edit}\" --cancel-button \"${cancel}\" --menu \
+\"\n${manual_part_msg}\n\n${dev_menu_header}\" 21 68 9 \\" >/tmp/gdl/part.sh
     fi
     counter=1
     until (( counter > device_count )); do
@@ -1860,9 +1636,9 @@ Keyboard \"on\"\nOption \"XkbLayout\" \"${KEYMAP}\"\nEndSection" \
   log "Set system keymap: ${KEYMAP}"
 
   # Time zone and hardware clock config
-  arch-chroot /mnt ln -sf /usr/share/zoneinfo/"${ZONE}" /etc/localtime
+  arch-chroot /mnt ln -sf /usr/share/zoneinfo/"${TIME_ZONE}" /etc/localtime
   arch-chroot /mnt hwclock --systohc # to generate /etc/adjtime
-  log "Set system time zone: ${ZONE}"
+  log "Set system time zone: ${TIME_ZONE}"
 
   # Firewall, network, and bluetooth config
   arch-chroot /mnt ufw enable
