Check for non-existent AUR packages

diff --git a/gdl b/gdl
--- a/gdl
+++ b/gdl
@@ -2377,8 +2377,10 @@ root ALL=(yaybuilder) NOPASSWD: ALL' >/mnt/etc/sudoers.d/yaybuilder
     for package in ${AUR_PACKAGES}; do
       log "* Installing '${package}'..."
       dragonsay "Installing ${package}..."
-      if ! arch-chroot /mnt sudo -u yaybuilder yay -Syu "${package}" --needed \
-          --noconfirm; then
+      if ! arch-chroot /mnt sudo -u yaybuilder yay -Si "${package}"; then
+        log_error "Unable to find '${package}'"
+      elif ! arch-chroot /mnt sudo -u yaybuilder yay -Syu "${package}" \
+          --needed --noconfirm; then
         log_error "Installation of '${package}' failed"
         if [[ "${package}" == 'matcha-gtk-theme' ||
               "${package}" == 'breeze-amber-cursor-theme' ||
